feat: Search filter for icons(#43)
Pradumnasaraf/LinkFree-CLI pull request #53
Opened 2023-03-01 18:26 UTC by PratikDey

## 🛠️ Fixes Issue

Closes #43 

## 👨‍💻 Changes proposed
Added autocomplete feature for selecting icons

## ✔️ Check List (Check all the applicable boxes) 

- [x ] My code follows the code style of this project.
- [x ] This PR does not contain plagiarized content.
- [x ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots

2023-03-02 06:02 UTC, Ananya2001-an submitted a review, later dismissed
Looks awesome! Thanks for your contribution 👍

2023-03-02 06:03 UTC, Ananya2001-an commented
Hey @Pradumnasaraf can you also review the changes.

2023-03-02 06:16 UTC, Ananya2001-an commented
There is just one issue that I think we need to look into that is when we show the icons users might not know that they can actually search by typing. It shows a cursor but it just might not catch their eye. What do you think @PratikDey @Pradumnasaraf ?

![image](https://user-images.githubusercontent.com/55504616/222346438-5854c0b4-b8f4-46e3-bd0c-19f47f83c99e.png)

https://www.awesomescreenshot.com/video/15244139?key=c020dc53af47746365f77df189e7f3c3

2023-03-02 06:29 UTC, Pradumnasaraf commented
Hey, 
First, I didn't know we had a type of type: "autocomplete"`. Learned something new. 

But I think, we can't use this one because the prompt message get disappeared and the user will not understand what should they do also the whole terminal is filled up with options.

So we need need to implement this, as mentioned in the issue.
https://www.npmjs.com/package/enquirer#autocomplete-prompt
![Screenshot 2023-03-02 at 11 56 06 AM](https://user-images.githubusercontent.com/51878265/222348550-cb3f45e6-bab1-4ae9-9651-6b10b3513aa4.png)

2023-03-02 06:29 UTC, Pradumnasaraf reviewed
Hey, 
First, I didn't know we had a type of `type: "autocomplete"`. Learned something new. 

But I think, we can't use this one because the prompt message get disappeared and the user will not understand what should they do also the whole terminal is filled up with options.

So we need need to implement this, as mentioned in the issue.
https://www.npmjs.com/package/enquirer#autocomplete-prompt
![Screenshot 2023-03-02 at 11 56 06 AM](https://user-images.githubusercontent.com/51878265/222348550-cb3f45e6-bab1-4ae9-9651-6b10b3513aa4.png)

2023-03-02 06:45 UTC, Ananya2001-an commented
> Hey, First, I didn't know we had a type of `type: "autocomplete"`. Learned something new.
> 
> But I think, we can't use this one because the prompt message get disappeared and the user will not understand what should they do also the whole terminal is filled up with options.
> 
> So we need need to implement this, as mentioned in the issue. https://www.npmjs.com/package/enquirer#autocomplete-prompt ![Screenshot 2023-03-02 at 11 56 06 AM](https://user-images.githubusercontent.com/51878265/222348550-cb3f45e6-bab1-4ae9-9651-6b10b3513aa4.png)

Yeah I think that will be better as users will not know otherwise that they can type and search.

2023-03-02 16:16 UTC, PratikDey commented
Hi, @Ananya2001-an and @Pradumnasaraf , I have actually tried implementing Autocomplete as it is in documentation but I am getting errors trying to implement like that. If you folks can give me some pointers on how should I go on implementing this then that would be much helpful. Also sorry, I don't have much knowledge on javascript.

2023-03-02 16:26 UTC, Ananya2001-an commented
> Hi, @Ananya2001-an and @Pradumnasaraf , I have actually tried implementing Autocomplete as it is in documentation but I am getting errors trying to implement like that. If you folks can give me some pointers on how should I go on implementing this then that would be much helpful. Also sorry, I don't have much knowledge on javascript.

No worries @PratikDey Can you tell us the exact problem that you are facing while implementing it. Maybe we can guide you then. I think after creating an instance of Autocomplete you can try writing the prompt.run() command after all other prompts are asked. Just try and let me know if you are facing any issues. 

Also don't worry about JavaScript. Everyone is learning something new here. I sucked at JS too at one point. It's all about trial and error. ☺

2023-03-04 18:18 UTC, PratikDey commented
Hi, when I am trying to run autocomplete by calling it as a function I am getting this error
![image](https://user-images.githubusercontent.com/56970651/222922148-e6f76dd5-27e8-4111-bbbc-2dae35eab8f1.png)
and if I am calling the prompt in autocomplete function I am getting error like this
![image](https://user-images.githubusercontent.com/56970651/222922199-7d202d3c-4f0f-43af-9402-d2303ca973c5.png)

This is another approach I tried
![image](https://user-images.githubusercontent.com/56970651/222922304-54f09693-60f7-4528-b4af-8a1f6e814edc.png)

Am I making any mistakes here?

2023-03-04 18:25 UTC, Ananya2001-an commented
Following the last screenshot move the autocomplete variable outside the while loop and also remove the prompt where you have given choices as autocomplete. Instead call autocomplete.run() just after all the prompts. I hope you are understanding what I am saying ?

2023-03-04 20:41 UTC, PratikDey commented
Yes, it is working. Thank you. 
Sorry, I am not so good in Javascript, that is why I had to disturb you folks so much.
I'll be submitting a PR soon

2023-03-05 06:21 UTC, Ananya2001-an commented
> Yes, it is working. Thank you. Sorry, I am not so good in Javascript, that is why I had to disturb you folks so much. I'll be submitting a PR soon

No issues. We are maintainers for a reason 😉

2023-03-05 06:22 UTC, Ananya2001-an commented
Also @PratikDey no need to raise another PR you can make new commits to the same one.

2023-03-05 06:28 UTC, Pradumnasaraf commented
Yes, you can push the changes to this PR as you move forward (even if it's broken) so that we can see and give you feedback and test if you get stuck

2023-03-08 14:42 UTC, PratikDey commented
hi, this PR is ready for review

2023-03-08 15:04 UTC, Ananya2001-an commented
Hey @PratikDey I tested the code and there are some issues:
1. First of all the autocomplete variable should be created inside the addLinks/updateLinks function so that choices list is not empty else it will give undefined error.
2. Also the icon is not getting saved inside the link object for the JSON profile in this way. Have you tested the code properly?

I will suggest you to play around with the code a bit and see what impact it has on the results so that you can get a better understanding. Also I feel you can do something like this that I tried and just apply the same logic everywhere else. Just make sure to import AutoComplete module from enquirer package.

```
async function addlinks(bool) {
  icons = await geticons();
  const autocomplete = new AutoComplete({
    name: 'icon',
    message: 'Choose an icon (Search to see more options)',
    limit: 10,
    choices: icons
  })
  while (bool) {
    let answers = await prompt([
      {
        type: "input",
        name: "name",
        message: "What is the name of the link?",
      },
      {
        type: "input",
        name: "url",
        message: "What is the URL of the link?",
      }
    ]);
    await autocomplete.run()
    const confirm = await prompt({
      type: "confirm",
      name: "addLink",
      message: "Do you want to add another link?",
    })
    links.push({
      name: answers.name,
      url: answers.url,
      icon: autocomplete.state.input,
    });
    if (!confirm.addLink) {
      return links;
    }
  }
}
```

2023-03-09 10:30 UTC, Pradumnasaraf commented
Weirdly, I am losing notifications on GItHub. Thanks for answering, @Ananya2001-an.

Yes I agree, we need to break code the icon part into 3 section

```js
await prompt ([ ])
await autocomplete.run()
await prompt ([ ])

// the push the inputs

```

2023-03-09 10:34 UTC, Ananya2001-an commented
> Weirdly, I am losing notifications on GItHub. Thanks for answering, @Ananya2001-an.
> 
> Yes I agree, we need to break code the icon part into 3 sections (i.e break the prompt into two part as mentioned by Ananya)
> 
> ```js
> await prompt ([ ])
> await autocomplete.run()
> await prompt ([ ])
> 
> // the push the inputs
> 
> ```

Exactly just implement the same on all relevant functions and that should work.

2023-03-09 15:14 UTC, PratikDey commented
Hi, while going by same logic as @Ananya2001-an mentioned, the `autocomplete.run()` is not running for the 2nd time and also it is taking a random value present.
![image](https://user-images.githubusercontent.com/56970651/224068123-ad275ee5-9450-4b73-81b2-4850d4861222.png)

2023-03-09 16:26 UTC, Pradumnasaraf commented
> Hi, while going by same logic as @Ananya2001-an mentioned, the `autocomplete.run()` is not running for the 2nd time and also it is taking a random value present. ![image](https://user-images.githubusercontent.com/56970651/224068123-ad275ee5-9450-4b73-81b2-4850d4861222.png)

Can you push the code? So that we can try and provide you the feedbcak

2023-03-09 18:08 UTC, PratikDey commented
ye

> > Hi, while going by same logic as @Ananya2001-an mentioned, the autocomplete.run() is not running for the 2nd time and also it is taking a random value present.
> 
> Can you push the code? So that we can try and provide you with the feedback

Yeah done

2023-03-10 18:09 UTC, PratikDey commented
Hi @Pradumnasaraf , I have pushed the code. You can review it.

2023-03-10 18:55 UTC, Pradumnasaraf commented
Hey, @PratikDey, 

Thank you. Just allow me some time. A little bust with other works.

2023-03-11 10:43 UTC, Ananya2001-an commented
Hey @PratikDey I tested the code and yes you are right that on the second time it's closing abruptly. I too am confused as to why it's happening. Let's wait for @Pradumnasaraf to give his review. Also thank you for being consistent on this till now. 😊

2023-03-11 17:50 UTC, Pradumnasaraf requested changes
Hey,

I think I got the root cause. You have created an object `const autocomplete = new AutoComplete({})` outside of the while loop and we are trying to update the `const` and an `object` in next iteration, so I think it's not possible.

So here is the solution, to put the object creation inside the loop

```js
async function addlinks(bool) {
  icons = await geticons();

  while (bool) {
    let answers = await prompt([
      {
        type: "input",
        name: "name",
        message: "What is the name of the link?",
      },
      {
        type: "input",
        name: "url",
        message: "What is the URL of the link?",
      }
    ]);

    const autocomplete = new AutoComplete({
      name: 'icon',
      message: 'Choose an icon (Search to see more options)',
      limit: 10,
      choices: icons
    })
    await autocomplete.run()

    const confirm = await prompt([
      {
        type: "confirm",
        name: "addLink",
        message: "Do you want to add another link?",
      }
    ])
    links.push({
      name: answers.name,
      url: answers.url,
      icon: autocomplete.state.input,
    });
    if (!confirm.addLink) {
      return links;
    }
  }
}
```

2023-03-11 17:54 UTC, Pradumnasaraf commented
Also, fix this in `src/shared/questions/milestone.js`. It's causing error

```diff
- const { prompt } = require("enquirer");
+ const { promp, AutoComplete } = require("enquirer");
```

2023-03-11 17:55 UTC, Ananya2001-an commented
> Hey,
> 
> I think I got the root cause. You have created an object `const autocomplete = new AutoComplete({})` outside of the while loop and we are trying to update the `const` and an `object` in next iteration, so I think it's not possible.
> 
> So here is the solution, to put the object creation inside the loop
> 
> ```js
> async function addlinks(bool) {
>   icons = await geticons();
> 
>   while (bool) {
>     let answers = await prompt([
>       {
>         type: "input",
>         name: "name",
>         message: "What is the name of the link?",
>       },
>       {
>         type: "input",
>         name: "url",
>         message: "What is the URL of the link?",
>       }
>     ]);
>   // solution
>     const autocomplete = new AutoComplete({
>       name: 'icon',
>       message: 'Choose an icon (Search to see more options)',
>       limit: 10,
>       choices: icons
>     })
>     await autocomplete.run()
> 
>     const confirm = await prompt([
>       {
>         type: "confirm",
>         name: "addLink",
>         message: "Do you want to add another link?",
>       }
>     ])
>     links.push({
>       name: answers.name,
>       url: answers.url,
>       icon: autocomplete.state.input,
>     });
>     if (!confirm.addLink) {
>       return links;
>     }
>   }
> }
> ```

That seems right. Since first we have selected an icon and its value is set inside the object it's not letting you change it because of `const` declaration.

2023-03-11 17:58 UTC, Pradumnasaraf commented
> That seems right. Since first we have selected an icon and its value is set inside the object it's not letting you change it because of const declaration

Yes, I tried to use `let` but still doesn't work. I think we need a new object creation every time, so putting in that loop is the solution.

2023-03-11 18:04 UTC, Pradumnasaraf commented
Hey, @PratikDey. You can implement this https://github.com/Pradumnasaraf/LinkFree-CLI/pull/53#pullrequestreview-1335916140. Ping us if you need help

2023-03-13 17:39 UTC, PratikDey commented
Hi @Pradumnasaraf and @Ananya2001-an , I have made all the changes as requested. Still getting one issue in `socials.js` file.
When I am trying to update the socials already present in the json file, I am getting this error 
![image](https://user-images.githubusercontent.com/56970651/224783243-48002a1a-da15-4550-a818-4767778ce93d.png)

2023-03-13 17:41 UTC, Pradumnasaraf commented
Hey,

Great. Can push the changes? So that we can have a look at the problem.

2023-03-13 17:44 UTC, Pradumnasaraf commented
Oops. Gotcha. I missed the commit message. Thank you, we have a look.

2023-03-14 16:20 UTC, Pradumnasaraf requested changes

2023-03-14 16:20 UTC, Pradumnasaraf commented on src/shared/questions/links.js
> +    const { icon, updateLink } = await prompt([{
Also, you don't need to add icons in this

2023-03-14 16:20 UTC, Pradumnasaraf commented
Also, @Ananya2001-an you can guide better in this because you have done the update part.

2023-03-14 16:32 UTC, Pradumnasaraf commented
> > Also, @Ananya2001-an you can guide better in this because you have done the update part.
> 
> Sure I will look into it and tell u by tomorrow. Just caught up with some other work right now. BTW the changes you have pointed out are correct. They might the only reason for that issue earlier. Still I will recheck.

Sure, take your time. Yes, It's working after that change, but still need to check other things in that function.

2023-03-15 05:29 UTC, Ananya2001-an commented
Hey @Pradumnasaraf I just tested the code right now and it works fine. I guess that was the only issue. @PratikDey You can follow up with what Pradumna has mentioned before and make the required changes.

2023-03-15 07:22 UTC, Pradumnasaraf commented
Thanks for checking @Ananya2001-an .

Just a small question, we don't need to update anything in this part?
<img width="692" alt="Screenshot 2023-03-15 at 12 50 27 PM" src="https://user-images.githubusercontent.com/51878265/225235538-a44136d0-113b-427b-b31b-2997441d3d05.png">

2023-03-15 07:28 UTC, Ananya2001-an commented
> Thanks for checking @Ananya2001-an .
> 
> Just a small question, we don't need to update anything in this part?
> <img width="692" alt="Screenshot 2023-03-15 at 12 50 27 PM" src="https://user-images.githubusercontent.com/51878265/225235538-a44136d0-113b-427b-b31b-2997441d3d05.png">
> 
> **Edit:** No, I don't think so because we are adding data to empty `let links = [];` 👍 
> 

Yes. I guess this is it.

2023-03-16 18:58 UTC, PratikDey commented
Hi, even after doing the requested changes, the issue is still there.
Actually what is happening is that at the time of creating the json file, the socials are getting pushed into the `social` array and during update it is searching for `socials` array.

![image](https://user-images.githubusercontent.com/56970651/225725823-eedc2eae-054b-4951-8013-bd3aa478ae0f.png)

2023-03-16 19:19 UTC, PratikDey commented
Committed all the changes, you folks can give this PR a review and let me know if any more changes are required.

2023-03-17 09:10 UTC, Pradumnasaraf commented
Hey,

Yes, you pointed it out correctly. There is a bug in updating social. @Ananya2001-an can you have a look? 
I think after this fix we can merge this PR.

2023-03-17 09:38 UTC, Ananya2001-an commented
> Hey,
> 
> Yes, you pointed it out correctly. There is a bug in updating social. @Ananya2001-an can you have a look? 
> I think after this fix we can merge this PR.

Sure I will look

2023-03-17 11:27 UTC, Ananya2001-an commented
Hey @PratikDey just remove the changes made to updateJson file. It has to be `socials` only not `social`. Everything else is fine. @Pradumnasaraf you can also confirm.

2023-03-17 11:42 UTC, Pradumnasaraf commented
> Hey @PratikDey just remove the changes made to updateJson file. It has to be `socials` only not `social`. Everything else is fine. @Pradumnasaraf you can also confirm.

Hey,

The issue is that it's not finding any existing socials.

<img width="1471" alt="Screenshot 2023-03-17 at 5 09 29 PM" src="https://user-images.githubusercontent.com/51878265/225894977-50369df2-c04e-42bb-bf5c-87cdca1328e5.png">


**I think this is the issue**
<img width="1074" alt="Screenshot 2023-03-17 at 5 10 28 PM" src="https://user-images.githubusercontent.com/51878265/225895018-4b8cf019-7d62-4800-a85b-8df4bd01494d.png">

2023-03-17 11:48 UTC, Ananya2001-an commented
In updateJson there should be no changes made at all.

2023-03-17 11:53 UTC, Pradumnasaraf commented
> In updateJson there should be no changes made at all.

Ah, gotcha. It's working now. My Gitpod caches the changes by Pratik's PR I have to delete are re-run. Thank you, Ananya

2023-03-17 11:57 UTC, Ananya2001-an commented
No worries. Hey @PratikDey you can now make this last change so we can merge your PR.

2023-03-17 18:23 UTC, PratikDey commented
I have reverted back to the old code in `updatejson`. Did not make any change to socialmap issue

2023-03-18 09:44 UTC, Ananya2001-an approved these changes
Looks good!👍🏼 @Pradumnasaraf give your review too.

2023-03-18 12:23 UTC, Pradumnasaraf approved these changes
Looks good to merge :tada: Thank you for your patience and contribution. Let's ship v2.2

<img src="https://media.giphy.com/media/bZBmitwUwKtDa/giphy-downsized-large.gif" height=250>

2023-03-18 12:25 UTC, merged